import { useState } from "react";

function App() {

  const [accountNumber, setAccountNumber] = useState("");
  const [amount, setAmount] = useState("");

  const handlePayment = async () => {

    console.log("PAY BUTTON CLICKED");

    try {

      // STEP 1: Create Razorpay Order through our backend
      const response = await fetch(
        "http://localhost:8080/api/v1/payments/create-order",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            accountNumber: accountNumber,
            amount: Number(amount),
            description: "Test external payment"
          })
        }
      );

      console.log("Response status:", response.status);

      const data = await response.json();

      console.log("Backend Response:", data);


      // STEP 2: Razorpay Checkout options
      const options = {

        // Razorpay test key
        key: data.razorpayId,

        // Amount is converted from rupees to paise
        amount: data.amount * 100,

        currency: data.currency,

        name: "Banking App",

        description: "External Payment",

        // Order ID generated by our backend
        order_id: data.razorpayOrderId,


        // STEP 3: Payment successful
        handler: function (response) {

          console.log("Payment Successful!");

          console.log("Razorpay Payment ID:",
            response.razorpay_payment_id
          );

          console.log("Razorpay Order ID:",
            response.razorpay_order_id
          );

          console.log("Razorpay Signature:",
            response.razorpay_signature
          );

        },


        prefill: {
          name: "Krishna Rinke"
        },


        theme: {
          color: "#3399cc"
        }

      };


      // STEP 4: Create Razorpay Checkout object
      const razorpay = new window.Razorpay(options);


      // STEP 5: Open Razorpay window
      razorpay.open();

    } catch (error) {

      console.error("Payment Error:", error);

    }
  };


  return (
    <div style={{
      width: "400px",
      margin: "100px auto",
      padding: "30px",
      border: "1px solid #ddd",
      borderRadius: "10px"
    }}>

      <h2>Make External Payment</h2>


      <label>Account Number</label>

      <input
        type="text"
        value={accountNumber}
        onChange={(e) => setAccountNumber(e.target.value)}
        placeholder="Enter account number"
        style={{
          width: "100%",
          padding: "10px",
          margin: "10px 0 20px"
        }}
      />


      <label>Amount</label>

      <input
        type="number"
        value={amount}
        onChange={(e) => setAmount(e.target.value)}
        placeholder="Enter amount"
        style={{
          width: "100%",
          padding: "10px",
          margin: "10px 0 20px"
        }}
      />


      <button
        onClick={handlePayment}
        style={{
          width: "100%",
          padding: "12px",
          cursor: "pointer"
        }}
      >
        Pay Now
      </button>

    </div>
  );
}

export default App;